# Import Data

In [1]:
import pandas as pd

In [6]:
data = pd.read_csv("wpbc.data",header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,25,26,27,28,29,30,31,32,33,34
0,119513,N,31,18.02,27.60,117.50,1013.0,0.09489,0.1036,0.1086,...,139.70,1436.0,0.1195,0.1926,0.3140,0.1170,0.2677,0.08113,5.0,5
1,8423,N,61,17.99,10.38,122.80,1001.0,0.11840,0.2776,0.3001,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,3.0,2
2,842517,N,116,21.37,17.44,137.50,1373.0,0.08836,0.1189,0.1255,...,159.10,1949.0,0.1188,0.3449,0.3414,0.2032,0.4334,0.09067,2.5,0
3,843483,N,123,11.42,20.38,77.58,386.1,0.14250,0.2839,0.2414,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,2.0,0
4,843584,R,27,20.29,14.34,135.10,1297.0,0.10030,0.1328,0.1980,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,3.5,0

In [19]:
column_names = ['id', 'outcome', 'time', 
                'radiusA', 'textureA', 'perimeterA', 'areaA', 'smoothnessA',
                'compactnessA', 'concavityA', 'concaveptsA', 'symmetryA', 'fdimA',
                'radiusB', 'textureB', 'perimeterB', 'areaB', 'smoothnessB',
                'compactnessB', 'concavityB', 'concaveptsB', 'symmetryB', 'fdimB',
                'radiusC', 'textureC', 'perimeterC', 'areaC', 'smoothnessC',
                'compactnessC', 'concavityC', 'concaveptsC', 'symmetryC', 'fdimC',
                'tumorsize', 'lymphstat']



# changing column names onces the data has be imported
data.columns = column_names
data.head()

,id,outcome,time,radiusA,textureA,perimeterA,areaA,smoothnessA,compactnessA,concavityA,...,perimeterC,areaC,smoothnessC,compactnessC,concavityC,concaveptsC,symmetryC,fdimC,tumorsize,lymphstat
0,119513,N,31,18.02,27.60,117.50,1013.0,0.09489,0.1036,0.1086,...,139.70,1436.0,0.1195,0.1926,0.3140,0.1170,0.2677,0.08113,5.0,5
1,8423,N,61,17.99,10.38,122.80,1001.0,0.11840,0.2776,0.3001,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,3.0,2
2,842517,N,116,21.37,17.44,137.50,1373.0,0.08836,0.1189,0.1255,...,159.10,1949.0,0.1188,0.3449,0.3414,0.2032,0.4334,0.09067,2.5,0
3,843483,N,123,11.42,20.38,77.58,386.1,0.14250,0.2839,0.2414,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,2.0,0
4,843584,R,27,20.29,14.34,135.10,1297.0,0.10030,0.1328,0.1980,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,3.5,0

# Clean Data

# Encode Data

# Split Data (training and testing sets)

# Train Machine Learning Model

# Evaluate Model Performance